### ISSUE TITLE
Possibly clearer applet_tables

### ISSUE THREAD

**Issue by Akeboshiwind** [samuela/rustybox#20]
Do you think it would be clearer if the entrypoints used the full path names (here)[https://github.com/samuela/rustybox/blob/master/applets/applet_tables.rs#L424]?

Great work in cleaning up that file btw, it looks great now.

**Comment by samuela** [comment]
Do you mean using `crate::...::main_func` instead of `use` imports?

**Comment by Akeboshiwind** [comment]
Yeah.

The alternative is just using editor navigation or just scrolling up.
Neither of which are bad options.

**Comment by samuela** [comment]
Yeah I think the full crate names would be better, esp. since that will also fix the "unused import" warnings when using feature flags.

**Comment by samuela** [comment]
Ok, should be fixed in 571301140f6462ba5fe193050aade00a388f2cd4.
