### ISSUE TITLE
modprobe or modprobe_small?

### ISSUE THREAD

**Issue by pwFoo** [samuela/rustybox#26]
Hi,
I again try to move to rustybox because it would be easier to build (if musl / static build works) for custom needs.

With busybox binary I have some problems with modprobe_small which not handle (soft) deps as should.
Supports rustybox modprobe, modprobe_small or both?

**Comment by pwFoo** [comment]
Blocked by non-static build? :(
See #25

**Comment by samuela** [comment]
There are modprobe and modprobe_small implementations in https://github.com/samuela/rustybox/tree/master/modutils.

**Comment by pwFoo** [comment]
I play with busybox today and have a problem with soft dependencies :(

For example I try to load r8169 nic driver, but realtek.ko isn't loaded as pre dependency.
To get the nic working I need to do manually the following steps.
```
modprobe -r r8169
modprobe realtek
modprobe r8169
```

But it should work without manually reload the modules in the right order...
Maybe rustybox have the same problem... I also tried alpine linux based busybox + kmod without success...
So I'm not sure if it is modprobe_small related ...

**Comment by samuela** [comment]
Hmm, it sounds as though this is an issue with modprobe/modprobe_small. If the busybox version doesn't work for you, then the rustybox one won't either since the rustybox utilities have been transpiled from the busybox ones.

**Comment by samuela** [comment]
If busybox and rustybox versions of the same utilities don't perform identically then that's a bug.

**Comment by pwFoo** [comment]
I need to test it with kernel 4.x! Maybe it could be a kernel 5.x problem!

**Comment by pwFoo** [comment]
Tested different kernel versions. It fails with kernel 5.x and works fine with alpine linux-vanilla 4.9.x kernel!
- https://bugzilla.redhat.com/show_bug.cgi?id=1580079
- https://bugzilla.kernel.org/show_bug.cgi?id=204343

So shouldn't be a busybox bug...

**Comment by samuela** [comment]
Ok glad to hear you got it working!
