### ISSUE TITLE
Found rust unshare lib

### ISSUE THREAD

**Issue by pwFoo** [samuela/rustybox#27]
Hi, 
I have found a rust unshare repo: https://github.com/tailhook/unshare

Maybe it's interesting for compare between the native rust library and the converted code from busybox?

Regards

**Comment by samuela** [comment]
I'm not sure I totally understand the comparison? What benefit would the unshare library bring to rustybox?

**Comment by pwFoo** [comment]
I thought it could bei a better code Base for the same feature or could help to optimize the converted source code. But Just as library it make no sense.
