### ISSUE TITLE
Any plans for a windows build?

### ISSUE THREAD

**Issue by playerdefault** [samuela/rustybox#29]
I tried building it on windows without success. Are there any plans for a Windows version too? What might be the effort required for that?

**Comment by samuela** [comment]
Hey @playerdefault ! A lot of the internals of busybox, and by extension rustybox, are designed specifically around linux, but I would definitely be open to PRs that move us towards using more of the std libs and for more cross-platform support!

Ultimately I think the path towards more windows compatibility will involve splitting up rustybox into cargo workspaces and then pushing each subproject towards compiling on other platforms. That way it should be possible to compile only the tools that you want and still get useful things out of them, eg a rust implementation of curl that you can build and run on windows even if the entire rustybox project doesn't work.

**Comment by playerdefault** [comment]
this project seems to be abandoned. closing this thread here.
